INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TRANSMISSION_CHANNELS Transmission_Channels)

FIND_PATH(
    TRANSMISSION_CHANNELS_INCLUDE_DIRS
    NAMES Transmission_Channels/api.h
    HINTS $ENV{TRANSMISSION_CHANNELS_DIR}/include
        ${PC_TRANSMISSION_CHANNELS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TRANSMISSION_CHANNELS_LIBRARIES
    NAMES gnuradio-Transmission_Channels
    HINTS $ENV{TRANSMISSION_CHANNELS_DIR}/lib
        ${PC_TRANSMISSION_CHANNELS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TRANSMISSION_CHANNELS DEFAULT_MSG TRANSMISSION_CHANNELS_LIBRARIES TRANSMISSION_CHANNELS_INCLUDE_DIRS)
MARK_AS_ADVANCED(TRANSMISSION_CHANNELS_LIBRARIES TRANSMISSION_CHANNELS_INCLUDE_DIRS)

